### ISSUE TITLE
 Problems with messages and new rooms

### ISSUE THREAD

**Issue by jersonjunior** [kevinppaulo/rocketchat-whatsapp-integration#1]
I tested the integration and noticed that after the second contact every message opens a new room.

While I haven't removed all the finished chats, it doesn't stop opening new rooms.

![image](https://user-images.githubusercontent.com/7052700/86015239-af759200-b9f7-11ea-8bc3-734607061055.png)

**Comment by kevinppaulo** [comment]
Thanks for reporting Jerson! 
I tested and it seems that the first contact needs to be deleted for that not to happen. It happens because I assign the conversation id to the person's phone number, and when the second contact occurs, the Id already exists.

**Comment by jersonjunior** [comment]
```
Traceback (most recent call last):
  File "/opt/rocketchat-whatsapp-integration/src/visitor_management/visitor_map.py", line 7, in create_visitor_rid_file
    visitor_file = open("/opt/rocketchat-whatsapp-integration/src/visitor_map/{}".format(visitor_token), "r")
FileNotFoundError: [Errno 2] No such file or directory: '/opt/rocketchat-whatsapp-integration/src/visitor_map/556198002190'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/rocketchat-whatsapp-integration/src/visitor_management/visitor_map.py", line 11, in create_visitor_rid_file
    visitor_file = open("/opt/rocketchat-whatsapp-integration/src/visitor_map/{}".format(visitor_token), "w")
FileNotFoundError: [Errno 2] No such file or directory: '/opt/rocketchat-whatsapp-integration/src/visitor_map/556198002190'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 90, in msg_recv
    rid = create_visitor_rid_file(visitor)
  File "/opt/rocketchat-whatsapp-integration/src/visitor_management/visitor_map.py", line 16, in create_visitor_rid_file
    rid = visitor_file.read()
UnboundLocalError: local variable 'visitor_file' referenced before assignment
```

**Comment by kevinppaulo** [comment]
This fix is temporary, as rocket chat returns a new room with a random Id when a message is sent to an already closed room.
I opened an issue in the rocket chat repo: https://github.com/RocketChat/Rocket.Chat/issues/18123

**Comment by jersonjunior** [comment]
I opened another problem, you saved constants.py as constants.example.py, but now it worked, then I want to see with you I have an IBM Assistant implementation to incorporate in your project if you are like

**Comment by kevinppaulo** [comment]
I answered your latest issue. Maybe we can create a discord server or a telegram group?

**Comment by jersonjunior** [comment]
Telegram
