### ISSUE TITLE
Error customFields

### ISSUE THREAD

**Issue by jersonjunior** [kevinppaulo/rocketchat-whatsapp-integration#7]
Error when using customFields:

```
def create_visitor(message):
    return {
        "visitor":{
            "name": message["from"],
            "email": "",
            "token": message["from"],
            "department": "Suporte",
            "customFields": [{ "key": "address", "value": "Rocket.Chat street", "overwrite": "true" }],
        }
    }

```

**Error:** 

```
Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/ibm--QpjHyKc/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/root/.local/share/virtualenvs/ibm--QpjHyKc/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/root/.local/share/virtualenvs/ibm--QpjHyKc/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/root/.local/share/virtualenvs/ibm--QpjHyKc/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/root/.local/share/virtualenvs/ibm--QpjHyKc/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/root/.local/share/virtualenvs/ibm--QpjHyKc/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 124, in msg_recv
    visitor_token = visitor["visitor"]["token"]
KeyError: 'visitor'

```

**Comment by jersonjunior** [comment]
def create_visitor(message):
    return {
        "visitor":{
            "name": message["from"],
            "email": "",
            "token": message["from"],
            "department": "Suporte",
            "customFields": [{"key": "Test", "value": "Test", "key": "Session", "value": "Test1", "overwrite": True}]],
        }
    }
